### ISSUE TITLE
Using loottable injection #enhancement

### ISSUE THREAD

**Issue by Slomaxonical-907** [JoostMSoftware/Beastalium#3]
I suggest using fabric's loottable injection instead of overriding the entities loottables, especially considering that these are probably commonnly used(added to) mobs. This would be better for compatibility between ur mod and others. 
Take care!

**Comment by JoostMSoftware** [comment]
Thank you @Slomaxonical-907 for the feature and will implement in the coming feature PR I will add to the mod. You can track the progress then at this PR #2 if you would want to and thank you for this nice suggestion :heart: 

Have a good day!

**Comment by JoostMSoftware** [comment]
it's implemented into the latest commit in the PR, so if you want to double check you can and wish you a lovely day!
